name: first

on:
    workflow_dispatch: 

jobs:
    Second:
        name: Second
        uses: nadeemjazmawe/test_CI-CD/.github/workflows/second.yml@master
        
        
    Third:
        name: Third
        needs: Second
        uses: nadeemjazmawe/test_CI-CD/.github/workflows/third.yml@master
