name: Second Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    
    env:
      BUILD_CONFIGURATION: Release
      
    steps:
      
# ------------------------------------------------------------------------------------------------------
# Copy repo Code
# ------------------------------------------------------------------------------------------------------
      - uses: actions/checkout@v3
      
# ------------------------------------------------------------------------------------------------------
# Upload Artifacts 
# ------------------------------------------------------------------------------------------------------    
      - name: 'Upload static site content'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./
