name: Second Workflow

on:
  workflow_call:
  workflow_dispatch:
    

jobs:
  build:
    runs-on: windows-latest
      
    steps:    
# ------------------------------------------------------------------------------------------------------
# Copy repo Code
# ------------------------------------------------------------------------------------------------------
      - uses: actions/checkout@v3
      
# ------------------------------------------------------------------------------------------------------
# Upload Artifacts 
# ------------------------------------------------------------------------------------------------------    
      - name: 'Upload static site content'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./
