27 lines (21 sloc)  809 Bytes

name: Second Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
      
    steps:
      
# ------------------------------------------------------------------------------------------------------
# Download Airtifacts
# ------------------------------------------------------------------------------------------------------
      - name: Download Airtifacts
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
      
# ------------------------------------------------------------------------------------------------------
# Print path
# ------------------------------------------------------------------------------------------------------    
      - name: 'Print Path'
        run:
          dir
